#!/bin/bash

# define font formatting sequence
# text style (set)
font_reset="\033[0m"
font_bold="\033[1m"
font_dim="\033[2m"
font_italic="\033[3m"
font_underline="\033[4m"
font_blink="\033[5m"
font_reverse="\033[7m"
font_hide="\033[8m"
font_stroke="\033[9m"
# text style (unset)
font_nobold="\033[21m"
font_nodim="\033[22m"
font_noitalic="\033[23m"
font_nounderline="\033[24m"
font_noblink="\033[25m"
font_noreverse="\033[27m"
font_nohide="\033[28m"
font_nostroke="\033[29m"
# foreground color
font_black="\033[30m"
font_red="\033[31m"
font_green="\033[32m"
font_yellow="\033[33m"
font_blue="\033[34m"
font_magenta="\033[35m"
font_cyan="\033[36m"
font_white="\033[37m"
# background color
font_bg_black="\033[40m"
font_bg_red="\033[41m"
font_bg_green="\033[42m"
font_bg_yellow="\033[43m"
font_bg_blue="\033[44m"
font_bg_magenta="\033[45m"
font_bg_cyan="\033[46m"
font_bg_white="\033[47m"
# foreground color (light)
font_lightblack="\033[90m"
font_lightred="\033[91m"
font_lightgreen="\033[92m"
font_lightyellow="\033[93m"
font_lightblue="\033[94m"
font_lightmagenta="\033[95m"
font_lightcyan="\033[96m"
font_lightwhite="\033[97m"
# background color (light)
font_bg_lightblack="\033[100m"
font_bg_lightred="\033[101m"
font_bg_lightgreen="\033[102m"
font_bg_lightyellow="\033[103m"
font_bg_lightblue="\033[104m"
font_bg_lightmagenta="\033[105m"
font_bg_lightcyan="\033[106m"
font_bg_lightwhite="\033[107m"

# checkout if color not supported, and clear predefined colors
if ! tput setaf 1 &>/dev/null || ! [ -t 1 ] || [ "$TERM" == "dumb" ]; then
    # color not supported, clear predefined variables
    for var in $(compgen -v); do
        if [[ "$var" == font_* ]]; then
            unset "$var"
        fi
    done
fi

